from packages import *

class Layout:
	# this class contains methods to draw basic layout of MI Learning platform.

	def enable_html(self):
		print('Content-type:text/html\n\n')

	def draw_header(self):
		print('<!DOCTYPE html>')
		print('<html>')
		print(' <head>')
		print('     <meta charset="utf-8">')
		print('     <title>Anwendungen im Databanklabor</title>')
		print('     <link rel="stylesheet" type="text/css" href="../browser.css">')
		print('     <link rel="stylesheet" type="text/css" href="../styles.css">')
		print('     <script type="text/javascript" src="../jquery-2.1.1.min.js"></script>')
		print('     <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">')
		print('     <script src="//code.jquery.com/jquery-1.10.2.js"></script>')
		print('     <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>')
		print('     <script> function setImg(){')
		print('         var imgName = localStorage.getItem("imgName");')
		print('         document.getElementById("imgName").innerHTML = imgName;')
		print('     }</script>')

		print(' </head>')
		print('<body>')
		print(' <div id="wapper">')
		print('     <div id="header">')
		print('         <h1 id="headline">Lab Database</h1>')
		print('         <nav id="nav_main">')
		print('         <a href="/SQLTool/">SQL Tool</a>')
		print('         <a href="../" class="currentPage">Image Database</a>')
		print('         </nav>')
		print('         <div id="logoHSO">')
		print('             <a href="http://www.hs-offenburg.de" target="_blank"><img src="../bilder/logoHSO.gif" alt="Hochschule Offenburg"></a>')
		print('         </div>')
		print('         <img src="../bilder/line_top.png" id="line_top">')
		print('     </div>')
		print('     <img id="hand" src="../bilder/hand.png">')
		print('     <div id="nav_left">')
		print('         <div id="menuItem">')
		print('             <a href="../index.html" class="currentPage">Image Search</a><br>')
		print('             <a href="../Help/index.html">Help</a><br>')
		print('             <a href="../Admin Login/index.html">Admin Login</a>')
		print('         </div>')
		print('     </div>')
		print('     <div id="content">')
		print('		<div class="margin-left-50" >')
		print('         <h2>Content Based Image Retrieval</h2>')

	def draw_footer(self):
		print('         </div>')
		print('     </div>')
		print('     <footer>')
		print('         <img src="../bilder/line_bottom.png" id="line_bottom"><br>')
		print('			<img src="../bilder/license.png" id="license" >')
		print('         <p id="nameProf">Prof. Dr. Volker Sänger, <a id="mail" href="mailto:volker.saenger@hs-offenburg.de">volker.saenger@hs-offenburg.de</a>')
		print('         </p>')
		print('     </footer>')
		print(' </div>')
		print('</body>')
		print('<img src="https://webanalyse.hs-offenburg.de/piwik.php?idsite=11&rec=1" style="border:0" alt="" />')
		print('</html>')

	def draw_header_lab(self):
		print('<!DOCTYPE html>')
		print('<html>')
		print(' <head>')
		print('     <meta charset="utf-8">')
		print('     <title>Anwendungen im Databanklabor</title>')
		print('     <link rel="stylesheet" type="text/css" href="../browser.css">')
		print('     <link rel="stylesheet" type="text/css" href="../styles.css">')
		print('     <script type="text/javascript" src="../jquery-2.1.1.min.js"></script>')
		print('     <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">')
		print('     <script src="//code.jquery.com/jquery-1.10.2.js"></script>')
		print('     <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>')
		print('     <script> function setImg(){')
		print('         var imgName = localStorage.getItem("imgName");')
		print('         document.getElementById("imgName").innerHTML = imgName;')
		print('     }</script>')

		print(' </head>')
		print('<body>')
		print(' <div id="wapper">')
		print('     <div id="header">')
		print('         <h1 id="headline">Lab Database</h1>')
		print('         <nav id="nav_main">')
		print('         <a href="/SQLTool/">SQL Tool</a>')
		print('         <a href="../" class="currentPage">Lab Image Database</a>')
		print('         </nav>')
		print('         <div id="logoHSO">')
		print('             <a href="http://www.hs-offenburg.de" target="_blank"><img src="../bilder/logoHSO.gif" alt="Hochschule Offenburg"></a>')
		print('         </div>')
		print('         <img src="../bilder/line_top.png" id="line_top">')
		print('     </div>')
		print('     <img id="hand" src="../bilder/hand.png">')
		print('     <div id="nav_left">')
		print('         <div id="menuItem">')
		print('             <a href="../index.html" class="currentPage">Lab Image Database</a><br>')
		print('             <a href="../Help/index.html">Help</a><br>')
		print('         </div>')
		print('     </div>')
		print('     <div id="content">')

	def draw_footer_lab(self):
		print('     </div>')
		print('     <footer>')
		print('         <img src="../bilder/line_bottom.png" id="line_bottom"><br>')
		print('			<img src="../bilder/license.png" id="license" >')
		print('         <p id="nameProf">Prof. Dr. Volker Sänger, <a id="mail" href="mailto:volker.saenger@hs-offenburg.de">volker.saenger@hs-offenburg.de</a>')
		print('         </p>')
		print('     </footer>')
		print(' </div>')
		print('</body>')
		print('<img src="https://webanalyse.hs-offenburg.de/piwik.php?idsite=11&rec=1" style="border:0" alt="" />')
		print('</html>')
